name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: setup babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.10.163
          
      - name: babashka script
        id: bb_script
        run: bb main/test.clj
          
      # Print the output of the babashka script from the
      # `bb_script` step 
      - name: Get the script output
        run: echo "${{ steps.bb_script.outputs.bb_out }}"
             echo "$PATH"
